use autopsy_repo::{compute_snapshot_id, scan_repository};
use autopsy_tests::TestSandbox;
use std::fs;
use std::thread;
use std::time::Duration;

#[test]
fn test_e2e_snapshot_id_100_runs_determinism() {
    let sandbox = TestSandbox::new("det_100");

    // Populate a realistic repository structure
    sandbox.write_file(
        "src/index.ts",
        "import { add } from './math';\nconsole.log(add(1, 2));",
    );
    sandbox.write_file(
        "src/math.ts",
        "export function add(a: number, b: number): number { return a + b; }",
    );
    sandbox.write_file("src/types/index.d.ts", "export type Num = number;");
    sandbox.write_file("README.md", "# Synevid Test Project");
    sandbox.write_file(
        "package.json",
        r#"{"name": "test-pkg", "version": "1.0.0"}"#,
    );
    sandbox.write_file(
        "generated/schema.ts",
        "// @generated by protoc\nexport const V = 1;",
    );
    sandbox.write_file(
        "target/debug/bundle.js",
        "console.log('should be ignored');",
    );

    let config = sandbox.default_config();

    // Initial baseline scan
    let baseline = scan_repository(&sandbox.root, &config, "0.0.1", Some("main"))
        .expect("Baseline scan must succeed");

    assert_eq!(
        baseline.files.len(),
        6,
        "Expected exactly 6 included files (target/ ignored)"
    );
    assert!(!baseline.files.contains_key("target/debug/bundle.js"));
    assert!(baseline.files["generated/schema.ts"].is_generated);

    // Verify 100 consecutive runs yield identical snapshot IDs and digests
    for run in 1..=100 {
        let rerun = scan_repository(&sandbox.root, &config, "0.0.1", Some("main"))
            .unwrap_or_else(|e| panic!("Run {} failed: {:?}", run, e));

        assert_eq!(
            baseline.snapshot_id, rerun.snapshot_id,
            "Run {} failed: SnapshotId differs from baseline",
            run
        );
        assert_eq!(
            baseline.file_set_digest, rerun.file_set_digest,
            "Run {} failed: File set digest differs from baseline",
            run
        );
    }
}

#[test]
fn test_e2e_snapshot_id_independent_of_file_timestamps() {
    let sandbox = TestSandbox::new("timestamp_invariance");

    let file_path = sandbox.write_file("src/core.rs", "pub fn verify() -> bool { true }");
    let config = sandbox.default_config();

    let snapshot_before = scan_repository(&sandbox.root, &config, "0.0.1", Some("main"))
        .expect("Scan before touch must succeed");

    // Sleep briefly and re-write exact same content to update filesystem mtime
    thread::sleep(Duration::from_millis(50));
    fs::write(&file_path, "pub fn verify() -> bool { true }").unwrap();

    let snapshot_after = scan_repository(&sandbox.root, &config, "0.0.1", Some("main"))
        .expect("Scan after touch must succeed");

    assert_eq!(
        snapshot_before.snapshot_id, snapshot_after.snapshot_id,
        "Snapshot ID must NOT depend on file modification timestamps"
    );
    assert_eq!(
        snapshot_before.file_set_digest, snapshot_after.file_set_digest,
        "File set digest must NOT depend on file modification timestamps"
    );
}

#[test]
fn test_e2e_snapshot_id_changes_deterministically_on_mutation() {
    let sandbox = TestSandbox::new("mutation_detection");

    let file_path = sandbox.write_file("src/logic.py", "def check(): return 42");
    let config = sandbox.default_config();

    let initial = scan_repository(&sandbox.root, &config, "0.0.1", Some("main")).unwrap();

    // Mutate file content
    fs::write(&file_path, "def check(): return 43").unwrap();

    let mutated = scan_repository(&sandbox.root, &config, "0.0.1", Some("main")).unwrap();

    assert_ne!(
        initial.snapshot_id, mutated.snapshot_id,
        "Mutating source file content must change the snapshot ID"
    );
    assert_ne!(
        initial.file_set_digest, mutated.file_set_digest,
        "Mutating source file content must change the file set digest"
    );
}

#[test]
fn test_e2e_compute_snapshot_id_direct_algorithm() {
    let digest = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
    let cfg = "7b22726f6f7473223a5b222e225d7d";
    let ver = "0.0.1";

    let id1 = compute_snapshot_id(digest, cfg, ver);
    let id2 = compute_snapshot_id(digest, cfg, ver);

    assert_eq!(id1, id2);
    assert_eq!(
        id1.as_str().len(),
        64,
        "BLAKE3 hex digest length must be 64 characters"
    );
}
